project:
  type: book
  output-dir: _site

book:
  title: "BioStatica"
  subtitle: "Complete Guide to Biostatistics for Modern Research"
  author:
    - name: "Pawan Rama Mali"
      email: "prm@outlook.in"
      orcid: "0000-0000-0000-0000"
      affiliation: "TechWorksLab"
  date: today
  description: |
    A comprehensive, beginner-friendly biostatistics textbook covering foundational
    principles to modern methodologies used in cutting-edge biological research.
    Includes practical examples, R/Python code, and real-world applications.

  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - introduction.qmd
        - chapters/ch01-foundational-concepts.qmd
    - part: "Statistical Inference"
      chapters:
        - chapters/ch02-comparative-inference.qmd
        - chapters/ch03-multi-group-analysis.qmd
    - part: "Advanced Modeling"
      chapters:
        - chapters/ch04-interrelationships-modeling.qmd
        - chapters/ch05-design-power-considerations.qmd
    - part: "Specialized Methods"
      chapters:
        - chapters/ch06-specialized-modern-methods.qmd
    - references.qmd

  sidebar:
    style: floating
    background: light
    search: true
    collapse-level: 2
    tools:
      - icon: github
        href: https://github.com/PawanRamaMali/BioStatica
        text: "Source Code"
      - icon: download
        href: "BioStatica.pdf"
        text: "Download PDF"
      - icon: question-circle
        href: "https://github.com/PawanRamaMali/BioStatica/issues"
        text: "Get Help"

  navbar:
    background: primary
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/PawanRamaMali/BioStatica
        text: "Source Code"
      - icon: twitter
        href: https://twitter.com/biostatistica
        text: "Follow Updates"

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: |
      Copyright 2024, Pawan Rama Mali. Licensed under [MIT License](https://github.com/PawanRamaMali/BioStatica/blob/main/LICENSE).
    right: |
      Built with [Quarto](https://quarto.org/) and ❤️ for open science.
    border: true

  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, epub]

  cover-image: "assets/cover.png"
  favicon: "assets/favicon.ico"

format:
  html:
    theme:
      - cosmo
      - assets/custom.scss
    css: assets/styles.css
    mainfont: "Crimson Text"
    sansfont: "Source Sans 3"
    monofont: "JetBrains Mono"

    # Layout and navigation
    toc: true
    toc-depth: 4
    toc-expand: 2
    toc-title: "Contents"
    number-sections: true
    number-depth: 4
    number-offset: 0

    # Code settings
    code-fold: true
    code-tools:
      source: true
      toggle: true
      caption: "Code"
    code-copy: hover
    code-link: true
    code-line-numbers: false
    code-overflow: wrap
    highlight-style: github

    # Figure settings
    fig-width: 10
    fig-height: 7
    fig-format: retina
    fig-dpi: 300
    fig-align: center
    fig-cap-location: bottom

    # Interactive features
    embed-resources: false
    smooth-scroll: true
    anchor-sections: true
    link-external-newwindow: true
    link-external-icon: true
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true

    # Search and accessibility
    search: true

    # Comments (optional)
    comments:
      hypothesis: true

    # Social sharing
    twitter-card: true
    open-graph: true

  pdf:
    documentclass: book
    classoption: [oneside, openany]
    geometry:
      - top=1in
      - bottom=1in
      - left=1.2in
      - right=1in
    fontfamily: crimson
    fontsize: 11pt
    linestretch: 1.3
    toc: true
    toc-depth: 3
    lot: true  # List of tables
    lof: true  # List of figures
    number-sections: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    citecolor: blue
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhead[LE,RO]{\thepage}
          \fancyhead[LO]{\rightmark}
          \fancyhead[RE]{\leftmark}
          \fancyfoot[C]{}

  epub:
    toc: true
    toc-depth: 3
    number-sections: true
    epub-cover-image: "assets/cover.png"

execute:
  freeze: auto
  cache: true
  warning: false
  message: false
  echo: true
  eval: false
  output: false
  fig-show: "hold"
  fig-keep: "all"

bibliography: references.bib

crossref:
  fig-title: "Figure"
  tbl-title: "Table"
  eq-title: "Equation"

lang: en

editor: visual